### ISSUE TITLE
Request for Grade

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/saas-website#1]
Hi @hellachella,

For this project, I stuck to the basics, and for the most part, the site works. The biggest issue I've had is with respect to the navigation, and I haven't been able to remedy it (see below):

<img width="799" alt="Screen Shot 2019-04-18 at 9 12 11 PM" src="https://user-images.githubusercontent.com/19557909/56400022-89fbce80-621f-11e9-9644-5efdb94d9361.png">

There are headers, mains, footers, sections, div tags, icons, and links galore. The required elements, like tables and embedded components are present (although the latter are often hidden for my own convenience). Generally speaking, I've respected the accessibility rules, and have a pretty clear hierarchy throughout the site. I would say visually, it's not particularly daring or interesting, although it is nearly identical to the prototype from our Interaction Design course.

I would say that this site demonstrates an understanding of the content from this year, but also reflects the relatively small amount of time that was spent on it. Personally, I think it's worth an A-, but I leave that up to your discretion.

Have a wonderful summer!

MacKenzie

**Comment by hellachella** [comment]
Thanks MacKenzie!
